### ISSUE TITLE
Use pandas-datareader to read World Bank data and UN data

### ISSUE THREAD

**Issue by sarvonz** [EAPD-DRB/OG-ZAF#13]
We are writing codes that allow us to retrieve data from World Bank databank.

**Comment by SeaCelo** [comment]
This is a good issue for our data pipeline to be more general

**Comment by SeaCelo** [comment]
@sarvonz Can you include neonatal mortality in the series to be downloaded from WDI?
 [World Bank Series is here](https://data.worldbank.org/indicator/SH.DYN.NMRT)

**Comment by SeaCelo** [comment]
@sarvonz Here is the python package to access UN statistics data: [pandaSDMX](https://pandasdmx.readthedocs.io/en/v1.0/#)
