### ISSUE TITLE
Update installation instructions for ARM Macs (M1 and M2)

### ISSUE THREAD

**Issue by SeaCelo** [EAPD-DRB/OG-ZAF#15]
We've tested the process of installing OG-ZAF on a "clean" Mac with the M1 chip. This computer had no previous installation of python, Anaconda, or dependencies. We tried to follow the installation instructions as written in the [Read Me](https://github.com/EAPD-DRB/OG-ZAF). During the installation, we ran into a few problems: 

- Late in the process an error required that users install Xcode Tools. Users should do this as a first step: `xcode-select —install`
- Users should download the correct version of Anaconda and Python. The prominent link in the Anaconda page downloads the X86 version. Instead, users should go to the bottom of the installation page: [Go here](https://www.anaconda.com/products/distribution#Downloads). Then select the version for the M1 (ARM) instead of x86 (Intel). 
- With Anaconda for M1 chips installed, you will get an error when you try `conda env create -f environment.yml`. This is because the "MKL" library will not be found (it is an Intel-only library). [To fix this you must follow the instructions in this comment](https://github.com/EAPD-DRB/OG-ZAF/issues/3#issue-1410280233). 

There are significant performance gains to using the appropriate version of Anaconda and Python on ARM Macs. The speedup in tests is 1.6-1.7x.

The installation instructions should reflect the platform-specific steps. I don't think the installation scripts can be written to take platform-specific steps, but this would be the preferred solution as it would simplify the process for users.

**Comment by SeaCelo** [comment]
A full solution would probably involve creating a OG-CORE package for conda. The package can be installed with platform dependencies.  
[meta.yml](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors)
[recipes](https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html)
This is a much bigger change that would require testing on all platforms. For this issue I will focus on having instructions specific to the ARM Macs.

**Comment by sarvonz** [comment]
Adding to what @SeaCelo said, in my case with a "clean" Mac, after `xcode-select --install`, which install/upgrade the command line tool for Xcode, I did `pip install lxml`. There was an error during my first attempt to install the model which required the installation of lxml.

**Comment by SeaCelo** [comment]
Installing the ARM version of Anaconda, which installs the ARM version of Python, results in a **1.6-1.7x speedup**.

**Comment by rickecon** [comment]
This issue is a continuation of Issue #3. Therefore, we are closing Issue #3, and the thread will continue here.

cc: @SeaCelo

**Comment by SeaCelo** [comment]
This issue is resolved by PR #16

**Comment by SeaCelo** [comment]
OG-CORE has updated its dependencies and no longer requires the `mkl` package that was causing trouble. I'm reopening to update the installation instructions for OG-ZAF to more closely follow OG-CORE
