### ISSUE TITLE
Issue with openssl in setup.py

### ISSUE THREAD

**Issue by rickecon** [EAPD-DRB/OG-ZAF#26]
PR #25 had a commit right before it was merged that added `"openssl=1.1.1",` to `setup.py`. This was my fault that this snuck in as @SeaCelo was merging the PR, so it didn't get tested. This has two problems.
* In `setup.py`, pinning the package needs to have the following form with two equals signs: `"openssl==1.1.1"`
* Even with this specified correctly, which I have done in a new branch, the pip install of the `ogzaf` package through `pip install -e .` after creating the `ogzaf-dev` conda environment fails with the following message.
```
ERROR: Could not find a version that satisfies the requirement openssl==1.1.1 (from ogzaf) (from versions: none)
ERROR: No matching distribution found for openssl==1.1.1
```

When I activate the `ogzaf-dev` conda environment and type `conda list openssl`, I get the following:
```
# packages in environment at /Users/richardevans/opt/anaconda3/envs/ogzaf-dev:
#
# Name                    Version                   Build  Channel
openssl                   1.1.1s               h03a7124_1    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
```

This should be an easy fix, but I don't know what it is right now. @SeaCelo @sarvonz

**Comment by SeaCelo** [comment]
@rickecon If I remove line 30 from `setup.py` I can install and run the model using the new environment.
