### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by SeaCelo** [EAPD-DRB/OG-ZAF#35]
The current documentation is a placeholder from OG-USA and should be updated to reflect the new sources and methods used in OG-ZAF. This includes:

- Demographics
- Macroeconomic parameters
- Lifetime income profiles
- Sector calibration and sources

**Comment by NHgit213** [comment]
Earnings documentation is underway. See Pull Request #39

**Comment by SeaCelo** [comment]
completed with #40
