### ISSUE TITLE
Macro parameters updates to make

### ISSUE THREAD

**Issue by jdebacker** [EAPD-DRB/OG-ZAF#55]
`macro_params.py` currently pulls macroeconomic data from several sources. These include the World Bank World Development Indicators, FRED, the UN (currently unused due to changes in their API).

Despite this, we still have trouble finding values for $\alpha_T$ (total government transfers as a share of GDP) and $\alpha_G$ (government consumption expenditures).

We should clean up this file and see if we can put values to $\alpha_T$ and $\alpha_G$ with data from one of these databases.

**Comment by SeaCelo** [comment]
@jdebacker I'll spend some time updating and documenting these sources.

**Comment by SeaCelo** [comment]
Linking to previous discussion on `alpha_t` and `alpha_g` for reference:  https://github.com/EAPD-DRB/OG-ZAF/pull/17

Suggested changes were recommended in this comment: https://github.com/EAPD-DRB/OG-ZAF/pull/17#pullrequestreview-1209121677

For `alpha_t`:  we can compute the value using this GFS data: https://data.imf.org/?sk=b052f0f0-c166-43b6-84fa-47cccae3e219&hide_uv=1
For `alpha_g`: the source is this GFS data: https://data.imf.org/?sk=edb0cd70-0af3-40e1-a9c3-bdef83ee4d1e&hide_uv=1

### Some observations on these sources and definitions of the variables:

**Aggregate Transfers (`alpha_T` and `alpha_G`) a a share of GDP**
There are two possible data sources that do not match and require studying. They also have different country coverages

1. World Bank ASPIRE data: [Social Expenditure Indicators by type of Social Assistance Program](https://thedocs.worldbank.org/en/doc/b48fbbe1d8f0f2b91775cbe0abbd99c8-0380082021/original/EXP-SA-expenditure-GDP.xlsx)

2. IMF GFS Main Aggregates and Balances from GFS database: https://data.imf.org/?sk=0c63d18f-e3ca-475a-9dd9-f3ba72494fcf&hide_uv=1 (manual with variable definitions here: https://www.imf.org/external/Pubs/FT/GFS/Manual/2014/gfsfinal.pdf —see page 131 for definitions)

Note: for IMF data, use “social benefits”. Decide on using with or without social security benefits (column BX or DZ). The model uses social security as a separate input. 
Here is a good query: https://data.imf.org/?sk=43b7b966-d0f2-443c-a1bd-217bf0a16c7b&hide_uv=1
Here is a query for all countries: [https://data.imf.org/?sk=43 b7b966-d0f2-443c-a1bd-217bf0a16c7b&hide_uv=1](https://data.imf.org/?sk=43b7b966-d0f2-443c-a1bd-217bf0a16c7b&hide_uv=1)

cc: @jdebacker

**Comment by jdebacker** [comment]
Updates made in PR #57
