### ISSUE TITLE
Some South African references for OG-ZAF calibration to consider & Data automation opportunity

### ISSUE THREAD

**Issue by DaanSteenkamp** [EAPD-DRB/OG-ZAF#65]
This is a great initiative! Just a couple of comments.

## Calibration
For anyone that would like to enrich the calibrations used for SA, this paper is a useful reference to use for thinking about the SA calibration: 
https://link.springer.com/chapter/10.1007/978-3-030-35754-2_7 , see Tables 1-4 for comparisons across models estimated in SA. 

## Specific Research Questions, eg Basic Income Grants
We have a paper on basic income grants that you could look at as well: https://onlinelibrary.wiley.com/doi/full/10.1111/saje.12363

## Data Automation
One could use the public domain data from our platform Econdata.co.za using its R/Python package to automate access of some of the data concepts used. 

## Extra Modules
One can for example, industry output data is available from EconData, so users could embellish the model with new modules that extend the number of industries in the model etc. 

## Model Automation
If a research student is interested in working with us to create a web app that automates analysis to make it easy for students to use without knowing to code, please get in touch with us at Codera

**Comment by DaanSteenkamp** [comment]
Also worth adding that you can get summary of estimates of TFP and elasticity of substitution from this paper: https://www.resbank.co.za/content/dam/sarb/publications/working-papers/2018/8937/WP-1805.pdf

**Comment by rickecon** [comment]
@DaanSteenkamp. Thanks so much for these references. We look forward to incorporating Codera data streams into OG-ZAF's standard workflow.
