### ISSUE TITLE
Unable to Access Online UN-WIDER SAM File - HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by GuBenda** [EAPD-DRB/OG-ZAF#72]
I am encountering an error while running the input_output.py which tries to access an online SAM file. 

- Error Message: 

[/usr/local/lib/python3.10/dist-packages/ogzaf/input_output.py](https://localhost:8080/#) in <module>
      9 storage_options = {"User-Agent": "Mozilla/5.0"}
     10 SAM_path = "https://www.wider.unu.edu/sites/default/files/Data/SASAM-2015-Data-Resource.xlsx"
---> 11 SAM = pd.read_excel(
     12     SAM_path,
     13     sheet_name="Micro SAM 2015"

HTTPError: HTTP Error 403: Forbidden

- Possible Causes:
The server might be blocking the request due to security restrictions or requiring additional headers for authentication. Loading from a local path might be needed.

**Comment by SeaCelo** [comment]
Thanks @GuBenda. I confirmed this on my machine. Looks to be a common issue. I'll create a PR to use use a backup site in the same way we have the demographics data. This should be done anyway in case the online source is not working or changes.

**Comment by jdebacker** [comment]
Resolved with PR #73
