### ISSUE TITLE
Use UN Population forecasts in demographics.py

### ISSUE THREAD

**Issue by SeaCelo** [EAPD-DRB/OG-ZAF#8]
The current demographics.py code only takes recent data and generates its own series to compute the steady state and projections. It would be desirable to use the UN models for population, fertility, mortality, and immigration. 

UN Population publishes forecasts through 2100. UN Population forecasts are now available in 1-year increments and by age throughout the forecast period: [World Population Prospects 2022](https://population.un.org/wpp/).

[UN Data API](https://population.un.org/dataportal/about/dataapi) (implemented in #4).

**Comment by SeaCelo** [comment]
@rickecon I'm still interested in the calculation of the population steady state and transition path. The current approach seems to be predicated on not having much data and the need to create a SS as well as the pathway. However, with the transition to using the UN Population data and annual forecasts until 2100, would it be better to simply use this data? 

It seems to me that it would be possible to use the last year (2100) as the SS population distribution, and to use the annual data (2021-2099) as the pathway to the SS. This would replace the function `get_pop_objs()` and generate the `pop_dict` directly from data instead of computing it. Maybe for a longer term project?

**Comment by rickecon** [comment]
This is a bigger demographics refactoring project than the current PR #14. I am posting two comments made by @SeaCelo in PR #14.

In [this comment](https://github.com/EAPD-DRB/OG-ZAF/pull/14#issuecomment-1302562971), @SeaCelo said:
> To help understand the South African population profiles, here are the detailed profiles prepared by UN Population: [https://population.un.org/wpp/Graphs/DemographicProfiles/Line/710](https://population.un.org/wpp/Graphs/DemographicProfiles/Line/710)

In [this comment](https://github.com/EAPD-DRB/OG-ZAF/pull/14#issuecomment-1303543835), @SeaCelo said:
> I looked at the population trends for South Africa and the data is correct. South Africa experienced a big change in fertility and mortality due to a few causes. My quick search of the literature give some clues (preferences, risk aversion by women, HIV epidemic and mortality, etc). When we analyze the results, we will need to keep these factors in mind as the population structure has been affected by the large changes in the 2000s.

**Comment by SeaCelo** [comment]
`demographics.py` is now part of OG-CORE (#51). Closing
